name: Kinetic

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Initialize submodule
      run: git submodule update --init --recursive
    - name: Pull kinetic continer
      run: docker pull ros:kinetic
    - name: Run kinetic build
      run: docker run --rm -v `pwd`:/code ros:kinetic /code/build_ros1.sh
