name: build manylinux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Initialize submodule
      run: git submodule update --init --recursive

    # Build in manylinux aarch64 container
    - name: Build in manylinux aarch64 container
      run: docker run --rm -v `pwd`:/repo --rm safijari/manylinux_2_28:aarch64 /repo/build.sh
      
    # Build in manylinux x86_64 container
    - name: Build in manylinux x86_64 container
      run: docker run --rm -v `pwd`:/repo --rm safijari/manylinux_2_28:x86_64 /repo/build.sh

    # Tar up artifacts after both builds
    - name: Tar up artifacts
      run: tar -czf dist.tar.gz dist/

    # Upload the artifacts
    - uses: actions/upload-artifact@main
      with:
        name: dist
        path: dist/
