name: Build

on:
  push:
    branches:
      - python-devel
  pull_request:
    branches:
      - python-devel

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [x86_64, aarch64]  # Define the architectures for the build
    steps:
    - uses: actions/checkout@v1
    - name: Initialize submodule
      run: git submodule update --init --recursive

    # Build in manylinux aarch64 container
    - name: Build in manylinux aarch64 container
      run: docker run --rm -v `pwd`:/repo --rm safijari/manylinux_2_28:${{ matrix.architecture }} /repo/build.sh
      
    # Tar up artifacts after both builds
    - name: Tar up artifacts
      run: tar -czf dist.tar.gz dist/

    # Upload the artifacts
    - uses: actions/upload-artifact@main
      with:
        name: dist_${{ matrix.architecture }}
        path: dist_${{ matrix.architecture }}/
